DROP TABLE IF EXISTS promotions;
DROP TABLE IF EXISTS stories;
DROP TABLE IF EXISTS rentals;
DROP TABLE IF EXISTS souvenirs;
DROP TABLE IF EXISTS guides;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS hotels;
