-- ============================================================
-- Manual seed: Near Yogyakarta destinations
-- Run this in production where auto-seed is disabled.
-- Idempotent — safe to re-run (uses ON CONFLICT DO NOTHING).
-- ============================================================

INSERT INTO destinations (
    external_id, name, name_en, tagline, tagline_en, category, location, sub_region,
    images, rating, review_count, description, description_en, story, story_en,
    ticket_price, opening_hours, facilities, facilities_en, travel_tips, travel_tips_en,
    best_time, best_time_en, weather, latitude, longitude,
    reviews, partners, faqs, status
) VALUES

-- 14. BOROBUDUR TEMPLE (Magelang)
(
    'borobudur',
    'Borobudur Temple', 'Borobudur Temple',
    'The World''s Largest Buddhist Temple at Dawn', 'The World''s Largest Buddhist Temple at Dawn',
    'heritage', 'Magelang, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1590211702270-5e64e0a2e04f?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1621869606578-1561708a7e09?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1592021369622-35e0f8d4491c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.9, 12500,
    'Borobudur is the world''s largest Buddhist temple, built in the 9th century during the Sailendra dynasty. The monument consists of nine stacked platforms — six square and three circular — topped by a central dome. Over 2,672 relief panels and 504 Buddha statues adorn the temple, making it one of the greatest Buddhist monuments on earth. A UNESCO World Heritage Site since 1991.',
    'Borobudur is the world''s largest Buddhist temple, built in the 9th century during the Sailendra dynasty. The monument consists of nine stacked platforms — six square and three circular — topped by a central dome. Over 2,672 relief panels and 504 Buddha statues adorn the temple, making it one of the greatest Buddhist monuments on earth. A UNESCO World Heritage Site since 1991.',
    'Borobudur lay hidden for centuries under volcanic ash and jungle growth after being abandoned in the 14th century. Sir Thomas Stamford Raffles rediscovered it in 1814 during the British occupation of Java. The Indonesian government and UNESCO led a massive restoration from 1975 to 1982, involving over 600 workers dismantling and reassembling the entire structure stone by stone.',
    'Borobudur lay hidden for centuries under volcanic ash and jungle growth after being abandoned in the 14th century. Sir Thomas Stamford Raffles rediscovered it in 1814 during the British occupation of Java. The Indonesian government and UNESCO led a massive restoration from 1975 to 1982, involving over 600 workers dismantling and reassembling the entire structure stone by stone.',
    'IDR 375,000 (Foreign) / IDR 50,000 (Domestic) / Sunrise package: IDR 450,000',
    '06:30 AM – 05:00 PM Daily (Sunrise: 04:30 AM – 06:00 AM)',
    '["Sunrise Viewing Platform","Audio Guide Rental","Buddhist Meditation Area","Museum & Visitor Center","Wheelchair Access","Batik Workshops","Souvenir Market","Restaurants & Cafes","Mosque & Prayer Room"]'::jsonb,
    '["Sunrise Viewing Platform","Audio Guide Rental","Buddhist Meditation Area","Museum & Visitor Center","Wheelchair Access","Batik Workshops","Souvenir Market","Restaurants & Cafes","Mosque & Prayer Room"]'::jsonb,
    '["Book the sunrise package to see the misty dawn over stupas.","Wear a sarong (provided at entrance) out of respect for the sacred site.","Hire a certified guide — relief panels tell the story of Buddhism.","Arrive by 06:00 AM to avoid midday heat and crowds."]'::jsonb,
    '["Book the sunrise package to see the misty dawn over stupas.","Wear a sarong (provided at entrance) out of respect for the sacred site.","Hire a certified guide — relief panels tell the story of Buddhism.","Arrive by 06:00 AM to avoid midday heat and crowds."]'::jsonb,
    'May to October (Dry Season) for sunrise; avoid weekends for fewer crowds',
    'May to October (Dry Season) for sunrise; avoid weekends for fewer crowds',
    '{"temp":"25°C","condition":"Clear Dawn","status":"Excellent conditions for sunrise at Borobudur."}'::jsonb,
    -7.6079, 110.2038,
    '[{"id":"r1","userName":"Sophia Laurent","userAvatar":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150","rating":5,"date":"2026-06-10","comment":"Watching the sunrise over the misty stupas of Borobudur was the most spiritual experience of my life."}]'::jsonb,
    '[{"id":"bb-p1","name":"Manohara Hotel Borobudur","category":"hotel","image":"https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=600","rating":4.6,"price":"IDR 800,000 / night","distance":"0.5 km from temple","description":"The only hotel within the Borobudur Archaeological Park — includes sunrise access.","address":"Jl. Badrawarna, Borobudur, Magelang"}]'::jsonb,
    '[{"q":"Can I climb to the top?","a":"Yes. Visitors can climb to the top platform with a guide."},{"q":"Is the sunrise package worth it?","a":"Absolutely — watching dawn break over the stupas is unforgettable."}]'::jsonb,
    'published'
),

-- 15. MENDUT TEMPLE (Magelang)
(
    'mendut',
    'Mendut Temple', 'Mendut Temple',
    'Home of the Majestic 3-Meter Seated Buddha', 'Home of the Majestic 3-Meter Seated Buddha',
    'heritage', 'Magelang, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1590211702270-5e64e0a2e04f?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1592021369622-35e0f8d4491c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.7, 1200,
    'Candi Mendut is a 9th-century Mahayana Buddhist temple located 3 km east of Borobudur. It houses a magnificent 3-meter seated Buddha statue in the bhumisparsha mudra (earth-touching pose), flanked by statues of the Bodhisattvas Avalokitesvara and Vajrapani — among the finest stone carvings of their era.',
    'Candi Mendut is a 9th-century Mahayana Buddhist temple located 3 km east of Borobudur. It houses a magnificent 3-meter seated Buddha statue in the bhumisparsha mudra (earth-touching pose), flanked by statues of the Bodhisattvas Avalokitesvara and Vajrapani — among the finest stone carvings of their era.',
    'Mendut is the oldest of the three temples that form the Borobudur archaeological axis — running east to west from Mendut to Pawon to Borobudur. This alignment symbolizes the journey from worldly desire (Mendut) to purification (Pawon) to enlightenment (Borobudur), and was used as the route for the annual Waisak procession.',
    'Mendut is the oldest of the three temples that form the Borobudur archaeological axis — running east to west from Mendut to Pawon to Borobudur. This alignment symbolizes the journey from worldly desire (Mendut) to purification (Pawon) to enlightenment (Borobudur), and was used as the route for the annual Waisak procession.',
    'IDR 30,000 (Adult) / IDR 15,000 (Child)',
    '07:00 AM – 05:00 PM Daily',
    '["Buddha Statue Viewing Hall","Meditation Area","Small Museum","Souvenir Stalls","Parking Area","Restrooms"]'::jsonb,
    '["Buddha Statue Viewing Hall","Meditation Area","Small Museum","Souvenir Stalls","Parking Area","Restrooms"]'::jsonb,
    '["Combine with Borobudur and Pawon in one morning.","Visit during Waisak (May full moon) to see the torchlight procession.","The interior Buddha statue is best photographed in the morning light.","Part of the Borobudur ticket package — save your receipt."]'::jsonb,
    '["Combine with Borobudur and Pawon in one morning.","Visit during Waisak (May full moon) to see the torchlight procession.","The interior Buddha statue is best photographed in the morning light.","Part of the Borobudur ticket package — save your receipt."]'::jsonb,
    'May for Waisak festival; mornings year-round for best lighting',
    'May for Waisak festival; mornings year-round for best lighting',
    '{"temp":"27°C","condition":"Partly Cloudy","status":"Good conditions for temple exploration."}'::jsonb,
    -7.6049, 110.2306,
    '[{"id":"r1","userName":"Budi Santoso","userAvatar":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150","rating":5,"date":"2026-06-12","comment":"The giant Buddha inside is awe-inspiring — better than the photos suggest."}]'::jsonb,
    '[{"id":"mt-p1","name":"Mendut Heritage Homestay","category":"hotel","image":"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=600","rating":4.5,"price":"IDR 350,000 / night","distance":"1 km","description":"Traditional Javanese homestay steps from Mendut Temple.","address":"Ds. Mendut, Mungkid, Magelang"}]'::jsonb,
    '[{"q":"Is Mendut included in the Borobudur ticket?","a":"Yes, the Borobudur ticket package covers Mendut and Pawon."},{"q":"How long do I need to visit?","a":"30-45 minutes is enough to appreciate the temple."}]'::jsonb,
    'published'
),

-- 16. PAWON TEMPLE (Magelang)
(
    'pawon',
    'Pawon Temple', 'Pawon Temple',
    'The Jewel of the Borobudur Sacred Axis', 'The Jewel of the Borobudur Sacred Axis',
    'heritage', 'Magelang, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1590211702270-5e64e0a2e04f?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1592021369622-35e0f8d4491c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.6, 850,
    'Candi Pawon is an elegant 9th-century Buddhist temple perfectly positioned between Mendut and Borobudur on the sacred east-west axis. Though smaller than its neighbors, Pawon is renowned for its exquisite proportions and intricate Kala-Makara carvings. The temple likely served as a storehouse for sacred objects.',
    'Candi Pawon is an elegant 9th-century Buddhist temple perfectly positioned between Mendut and Borobudur on the sacred east-west axis. Though smaller than its neighbors, Pawon is renowned for its exquisite proportions and intricate Kala-Makara carvings. The temple likely served as a storehouse for sacred objects.',
    'Pawon''s name derives from the Javanese word ''pawon'' (kitchen), perhaps referring to the food offerings once prepared here for the Waisak procession. The temple was rediscovered in 1896 and underwent restoration between 1903 and 1908. The reliefs on its walls depict kalpataru (tree of life) panels flanked by celestial beings.',
    'Pawon''s name derives from the Javanese word ''pawon'' (kitchen), perhaps referring to the food offerings once prepared here for the Waisak procession. The temple was rediscovered in 1896 and underwent restoration between 1903 and 1908. The reliefs on its walls depict kalpataru (tree of life) panels flanked by celestial beings.',
    'IDR 25,000 (Adult) / IDR 10,000 (Child)',
    '07:00 AM – 04:00 PM Daily',
    '["Temple Viewing Area","Relief Panels","Small Garden","Parking Area","Restrooms"]'::jsonb,
    '["Temple Viewing Area","Relief Panels","Small Garden","Parking Area","Restrooms"]'::jsonb,
    '["A quick stop — 15-20 minutes is enough.","Best light for photos is late afternoon.","The kalpataru reliefs on the outer walls are exceptionally well-preserved.","Often missed by tourists — you''ll have it almost to yourself."]'::jsonb,
    '["A quick stop — 15-20 minutes is enough.","Best light for photos is late afternoon.","The kalpataru reliefs on the outer walls are exceptionally well-preserved.","Often missed by tourists — you''ll have it almost to yourself."]'::jsonb,
    'Afternoon for golden light; year-round',
    'Afternoon for golden light; year-round',
    '{"temp":"28°C","condition":"Sunny","status":"Nice weather for a short temple visit."}'::jsonb,
    -7.6062, 110.2192,
    '[{"id":"r1","userName":"Yuki Tanaka","userAvatar":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150","rating":4.5,"date":"2026-06-10","comment":"Small but perfectly proportioned. The carvings are incredibly detailed."}]'::jsonb,
    '[{"id":"pw-p1","name":"Pawon Art Village","category":"attraction","image":"https://images.unsplash.com/photo-1518895949257-7621c3c786d7?q=80&w=600","rating":4.3,"price":"Free entry","distance":"0.3 km","description":"Local artisan village with batik and wood carving workshops.","address":"Ds. Wanurejo, Borobudur, Magelang"}]'::jsonb,
    '[{"q":"Do I need a separate ticket?","a":"No. It''s covered by the Borobudur ticket package."},{"q":"Can I walk here from Borobudur?","a":"Yes, it''s a pleasant 2 km walk through rice paddies."}]'::jsonb,
    'published'
),

-- 17. PLAOSAN TEMPLE (Klaten)
(
    'plaosan',
    'Plaosan Temple', 'Plaosan Temple',
    'The Twin Temple of Grace and Elegance', 'The Twin Temple of Grace and Elegance',
    'heritage', 'Klaten, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.7, 1100,
    'Candi Plaosan is a stunning 9th-century Buddhist temple complex located just 1 km east of Prambanan. Built during the reigns of Rakai Pikatan and Queen Pramodhawardhani of the Mataram Kingdom, the complex features twin main temples (Plaosan Lor and Plaosan Kidul), adorned with elegant reliefs and crowned with distinctive stupas.',
    'Candi Plaosan is a stunning 9th-century Buddhist temple complex located just 1 km east of Prambanan. Built during the reigns of Rakai Pikatan and Queen Pramodhawardhani of the Mataram Kingdom, the complex features twin main temples (Plaosan Lor and Plaosan Kidul), adorned with elegant reliefs and crowned with distinctive stupas.',
    'Plaosan was built as a symbol of reconciliation between the Hindu Sanjaya and Buddhist Sailendra dynasties, whose union was sealed through the marriage of King Pikatan (Hindu) to Princess Pramodhawardhani (Buddhist). The temple''s unique design blends both traditions, with Hindu-style door guardians protecting a Buddhist sanctuary.',
    'Plaosan was built as a symbol of reconciliation between the Hindu Sanjaya and Buddhist Sailendra dynasties, whose union was sealed through the marriage of King Pikatan (Hindu) to Princess Pramodhawardhani (Buddhist). The temple''s unique design blends both traditions, with Hindu-style door guardians protecting a Buddhist sanctuary.',
    'IDR 30,000 (Adult) / IDR 15,000 (Child)',
    '07:00 AM – 05:00 PM Daily',
    '["Twin Temple Complex","Buddhist Stupa Garden","Relief Panel Walkways","Parking Area","Food Stalls","Restrooms"]'::jsonb,
    '["Twin Temple Complex","Buddhist Stupa Garden","Relief Panel Walkways","Parking Area","Food Stalls","Restrooms"]'::jsonb,
    '["Visit right after sunrise for golden light on the twin temples.","Much quieter than Prambanan — you may have the place to yourself.","The south temple (Plaosan Kidul) has the best-preserved reliefs.","Combine with Prambanan and Sewu Temple in one trip."]'::jsonb,
    '["Visit right after sunrise for golden light on the twin temples.","Much quieter than Prambanan — you may have the place to yourself.","The south temple (Plaosan Kidul) has the best-preserved reliefs.","Combine with Prambanan and Sewu Temple in one trip."]'::jsonb,
    'May to October (Dry Season); early morning for best light and fewer crowds',
    'May to October (Dry Season); early morning for best light and fewer crowds',
    '{"temp":"27°C","condition":"Partly Cloudy","status":"Good conditions for exploring the temple complex."}'::jsonb,
    -7.7467, 110.5047,
    '[{"id":"r1","userName":"Yuki Tanaka","userAvatar":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150","rating":5,"date":"2026-06-18","comment":"Less crowded than Prambanan but equally beautiful. The twin temples are stunning at sunrise."}]'::jsonb,
    '[{"id":"pl-p1","name":"Plaosan Heritage Guide","category":"guide","image":"https://images.unsplash.com/photo-1544717297-fa95b6ee9643?q=80&w=600","rating":4.7,"price":"IDR 100,000 / tour","distance":"On-Site","description":"Local guides offering deep insight into Plaosan''s unique Hindu-Buddhist fusion.","address":"Plaosan, Prambanan, Klaten"}]'::jsonb,
    '[{"q":"Is Plaosan included in the Prambanan ticket?","a":"No, it requires a separate ticket but is very affordable."},{"q":"How much time do I need?","a":"About 1 hour to fully explore both temples and the grounds."}]'::jsonb,
    'published'
),

-- 18. SEWU TEMPLE (Klaten)
(
    'sewu',
    'Sewu Temple', 'Sewu Temple',
    'The Grand Buddhist Monastery of Prambanan', 'The Grand Buddhist Monastery of Prambanan',
    'heritage', 'Klaten, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1621869606578-1561708a7e09?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.7, 1800,
    'Candi Sewu is an 8th-century Mahayana Buddhist temple complex just 800 meters north of Prambanan. The second-largest Buddhist temple compound in Indonesia after Borobudur, Sewu features a central temple surrounded by 240 smaller perwara (guardian) temples arranged in a mandala pattern, showcasing the pinnacle of Sailendra architecture.',
    'Candi Sewu is an 8th-century Mahayana Buddhist temple complex just 800 meters north of Prambanan. The second-largest Buddhist temple compound in Indonesia after Borobudur, Sewu features a central temple surrounded by 240 smaller perwara (guardian) temples arranged in a mandala pattern, showcasing the pinnacle of Sailendra architecture.',
    'Sewu, meaning ''a thousand'' in Javanese, refers to the countless guardian statues that once filled its 240 subsidiary temples. Built before Borobudur, Sewu was the largest Buddhist monastery complex in ancient Java. An inscription from 792 AD mentions King Indra of the Sailendra dynasty consecrating the temple to the bodhisattva Manjusri.',
    'Sewu, meaning ''a thousand'' in Javanese, refers to the countless guardian statues that once filled its 240 subsidiary temples. Built before Borobudur, Sewu was the largest Buddhist monastery complex in ancient Java. An inscription from 792 AD mentions King Indra of the Sailendra dynasty consecrating the temple to the bodhisattva Manjusri.',
    'IDR 30,000 (Adult) / IDR 15,000 (Child) — often covered by Prambanan combo ticket',
    '07:00 AM – 05:00 PM Daily',
    '["Main Temple (Central Shrine)","240 Perwara Temples","Buddha Statue Niches","Stone Relief Corridors","Parking Area","Food Stalls","Restrooms"]'::jsonb,
    '["Main Temple (Central Shrine)","240 Perwara Temples","Buddha Statue Niches","Stone Relief Corridors","Parking Area","Food Stalls","Restrooms"]'::jsonb,
    '["Buy the Prambanan combo ticket that includes Sewu — great value.","Early morning (07:00 AM) for the best photos with no crowds.","Walk from Prambanan — it''s only 800 meters through a pleasant path.","Climb the central temple stairs for a view of the entire mandala layout."]'::jsonb,
    '["Buy the Prambanan combo ticket that includes Sewu — great value.","Early morning (07:00 AM) for the best photos with no crowds.","Walk from Prambanan — it''s only 800 meters through a pleasant path.","Climb the central temple stairs for a view of the entire mandala layout."]'::jsonb,
    'May to October (Dry Season); morning for best lighting on the stone carvings',
    'May to October (Dry Season); morning for best lighting on the stone carvings',
    '{"temp":"28°C","condition":"Sunny","status":"Perfect for exploring the vast temple complex."}'::jsonb,
    -7.7439, 110.4967,
    '[{"id":"r1","userName":"Sophia Laurent","userAvatar":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150","rating":5,"date":"2026-06-15","comment":"The mandala layout is breathtaking. I can''t believe this gem is right next to Prambanan yet so quiet."}]'::jsonb,
    '[{"id":"sw-p1","name":"Prambanan Heritage Hotel","category":"hotel","image":"https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=600","rating":4.4,"price":"IDR 700,000 / night","distance":"2 km","description":"Heritage hotel with direct views of Prambanan and Sewu temples.","address":"Jl. Raya Solo-Yogya, Prambanan, Klaten"}]'::jsonb,
    '[{"q":"Is Sewu included in the Prambanan ticket?","a":"Yes, if you buy the Prambanan + Sewu combo ticket."},{"q":"How long to explore Sewu?","a":"Plan for 1–1.5 hours to fully appreciate the complex."}]'::jsonb,
    'published'
),

-- 19. ROWO JOMBOR (Klaten)
(
    'rowojombor',
    'Rowo Jombor', 'Rowo Jombor',
    'Floating Stalls and Lakeside Serenity', 'Floating Stalls and Lakeside Serenity',
    'nature', 'Klaten, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.4, 1900,
    'Rowo Jombor is a scenic artificial lake in Klaten, famous for its unique floating warungs (food stalls) where visitors can enjoy fresh seafood and local specialties while seated on bamboo rafts floating on the water. Surrounded by lush green hills and rice paddies, it''s a peaceful escape just 30 minutes from Yogyakarta.',
    'Rowo Jombor is a scenic artificial lake in Klaten, famous for its unique floating warungs (food stalls) where visitors can enjoy fresh seafood and local specialties while seated on bamboo rafts floating on the water. Surrounded by lush green hills and rice paddies, it''s a peaceful escape just 30 minutes from Yogyakarta.',
    'Rowo Jombor was originally a low-lying area that naturally flooded over time. Local fishermen began selling snacks from their boats, which evolved into the floating market concept. The floating warungs became a popular attraction, with visitors arriving by paddle boat to eat, shop, and enjoy the relaxed atmosphere on the water.',
    'Rowo Jombor was originally a low-lying area that naturally flooded over time. Local fishermen began selling snacks from their boats, which evolved into the floating market concept. The floating warungs became a popular attraction, with visitors arriving by paddle boat to eat, shop, and enjoy the relaxed atmosphere on the water.',
    'IDR 10,000 / person (parking additional)',
    '07:00 AM – 06:00 PM Daily',
    '["Floating Warungs (Food Stalls)","Paddle Boat Rentals","Lakeside Walking Path","Children''s Play Area","Parking Area","Restrooms","Mosque"]'::jsonb,
    '["Floating Warungs (Food Stalls)","Paddle Boat Rentals","Lakeside Walking Path","Children''s Play Area","Parking Area","Restrooms","Mosque"]'::jsonb,
    '["Come hungry — the floating warungs serve excellent fresh fish, crabs, and fried tempeh.","Rent a paddle boat to reach the floating stalls (IDR 30,000/hour).","Late afternoon is the best time for cooler weather and sunset views.","Weekdays are much quieter than weekends."]'::jsonb,
    '["Come hungry — the floating warungs serve excellent fresh fish, crabs, and fried tempeh.","Rent a paddle boat to reach the floating stalls (IDR 30,000/hour).","Late afternoon is the best time for cooler weather and sunset views.","Weekdays are much quieter than weekends."]'::jsonb,
    'Late afternoon (03:00–05:00 PM) for sunset; weekdays for fewer crowds',
    'Late afternoon (03:00–05:00 PM) for sunset; weekdays for fewer crowds',
    '{"temp":"29°C","condition":"Partly Cloudy","status":"Good afternoon for boating and dining on the water."}'::jsonb,
    -7.7170, 110.5830,
    '[{"id":"r1","userName":"Budi Santoso","userAvatar":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150","rating":4.5,"date":"2026-07-02","comment":"Eating fresh grilled fish on a bamboo raft floating on the lake — such a unique experience!"}]'::jsonb,
    '[{"id":"rj-p1","name":"Rowo Jombor Floating Cafe","category":"restaurant","image":"https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=600","rating":4.3,"price":"IDR 30,000 – 70,000 / person","distance":"On-Site","description":"Popular floating warung serving fresh lake fish and traditional Javanese dishes.","address":"Rowo Jombor, Klaten"}]'::jsonb,
    '[{"q":"Can I swim in the lake?","a":"Swimming is not recommended as it''s used for fishing and boating."},{"q":"Are there vegetarian options at the floating warungs?","a":"Yes, there are vegetarian options including fried tempeh and tahu."}]'::jsonb,
    'published'
),

-- 20. WADUK GAJAH MUNGKUR (Wonogiri)
(
    'gajahmungkur',
    'Waduk Gajah Mungkur', 'Waduk Gajah Mungkur',
    'The Great Reservoir of Wonogiri', 'The Great Reservoir of Wonogiri',
    'nature', 'Wonogiri, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.5, 2400,
    'Waduk Gajah Mungkur (Gajah Mungkur Reservoir) is a massive reservoir spanning over 8,800 hectares in Wonogiri. Built in the 1970s, it serves as a vital irrigation source and hydropower facility while offering stunning water landscapes with scattered islands. Visitors enjoy boat tours, water sports, camping, and bird watching against a backdrop of rolling hills.',
    'Waduk Gajah Mungkur (Gajah Mungkur Reservoir) is a massive reservoir spanning over 8,800 hectares in Wonogiri. Built in the 1970s, it serves as a vital irrigation source and hydropower facility while offering stunning water landscapes with scattered islands. Visitors enjoy boat tours, water sports, camping, and bird watching against a backdrop of rolling hills.',
    'The reservoir was constructed between 1974 and 1981 as part of the Bengawan Solo river management project. The construction submerged several villages, and over 1,000 families were relocated. The name ''Gajah Mungkur'' comes from a nearby hill that resembles a crouching elephant. Today, the reservoir has become a vital economic and tourism hub for Wonogiri.',
    'The reservoir was constructed between 1974 and 1981 as part of the Bengawan Solo river management project. The construction submerged several villages, and over 1,000 families were relocated. The name ''Gajah Mungkur'' comes from a nearby hill that resembles a crouching elephant. Today, the reservoir has become a vital economic and tourism hub for Wonogiri.',
    'IDR 10,000 / person / IDR 50,000 – 200,000 for boat tours',
    '06:00 AM – 06:00 PM Daily',
    '["Reservoir Viewpoint","Boat Tours (Motor & Paddle)","Water Sports","Camping Grounds","Bird Watching Tower","Lakeside Restaurants","Parking Area","Restrooms"]'::jsonb,
    '["Reservoir Viewpoint","Boat Tours (Motor & Paddle)","Water Sports","Camping Grounds","Bird Watching Tower","Lakeside Restaurants","Parking Area","Restrooms"]'::jsonb,
    '["Take the sunset boat tour for breathtaking views over the reservoir islands.","Visit during the dry season when the water level is stable.","Bring binoculars for bird watching — over 60 species have been recorded.","The floating restaurants serve excellent fresh-water fish."]'::jsonb,
    '["Take the sunset boat tour for breathtaking views over the reservoir islands.","Visit during the dry season when the water level is stable.","Bring binoculars for bird watching — over 60 species have been recorded.","The floating restaurants serve excellent fresh-water fish."]'::jsonb,
    'May to September (Dry Season) for boating; early morning for bird watching',
    'May to September (Dry Season) for boating; early morning for bird watching',
    '{"temp":"28°C","condition":"Clear","status":"Perfect conditions for a boat tour on the reservoir."}'::jsonb,
    -7.8970, 110.9270,
    '[{"id":"r1","userName":"Yuki Tanaka","userAvatar":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150","rating":4.5,"date":"2026-06-22","comment":"The vast reservoir with green islands scattered across the water is a beautiful sight. The sunset cruise was fantastic."}]'::jsonb,
    '[{"id":"gm-p1","name":"Gajah Mungkur Boating Club","category":"rental","image":"https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=600","rating":4.4,"price":"IDR 100,000 – 200,000 / tour","distance":"On-Site","description":"Professional boat tours with experienced local captains.","address":"Jalan Waduk Gajah Mungkur, Wonogiri"}]'::jsonb,
    '[{"q":"Can I camp at the reservoir?","a":"Yes, designated camping areas are available by the lakeshore."},{"q":"Is it safe to swim?","a":"Swimming is not recommended — it''s a working reservoir."}]'::jsonb,
    'published'
),

-- 21. KERATON SURAKARTA (Solo)
(
    'keratonsolo',
    'Keraton Surakarta', 'Keraton Surakarta',
    'The Royal Palace of Solo — Tradition Meets Modernity', 'The Royal Palace of Solo — Tradition Meets Modernity',
    'heritage', 'Surakarta (Solo), Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1581456495146-65a71b2c8e52?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1566559631133-969041fc5583?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.6, 3500,
    'Keraton Surakarta Hadiningrat is the official palace of the Susuhunan (King) of Surakarta, built in 1744 by Pakubuwono II. The palace complex showcases exquisite Javanese royal architecture, sacred heirlooms, gamelan instruments, and remains the cultural heart of Solo. The palace museum holds one of the finest collections of Javanese art in existence.',
    'Keraton Surakarta Hadiningrat is the official palace of the Susuhunan (King) of Surakarta, built in 1744 by Pakubuwono II. The palace complex showcases exquisite Javanese royal architecture, sacred heirlooms, gamelan instruments, and remains the cultural heart of Solo. The palace museum holds one of the finest collections of Javanese art in existence.',
    'The Keraton was built after the Mataram Kingdom split in 1755 (Giyanti Treaty), dividing the kingdom into Yogyakarta and Surakarta. The palace grounds include the main pendopo (audience hall), the royal meditation chamber, and the Sasana Sewaka hall. The palace still actively hosts traditional ceremonies and cultural performances.',
    'The Keraton was built after the Mataram Kingdom split in 1755 (Giyanti Treaty), dividing the kingdom into Yogyakarta and Surakarta. The palace grounds include the main pendopo (audience hall), the royal meditation chamber, and the Sasana Sewaka hall. The palace still actively hosts traditional ceremonies and cultural performances.',
    'IDR 25,000 (Adult) / IDR 15,000 (Child) / Camera fee IDR 5,000',
    '08:30 AM – 03:30 PM Tuesday–Sunday (Closed Monday)',
    '["Royal Museum","Gamelan Performance Hall","Royal Carriage Collection","Batik Museum","Javanese Architecture Tour","Gift Shop","Clean Restrooms","Parking Area"]'::jsonb,
    '["Royal Museum","Gamelan Performance Hall","Royal Carriage Collection","Batik Museum","Javanese Architecture Tour","Gift Shop","Clean Restrooms","Parking Area"]'::jsonb,
    '["Visit on Saturday morning for the best cultural performances at the palace.","Hire a guide — the stories behind the artifacts are fascinating.","Don''t miss the museum''s keris (ceremonial dagger) collection.","Combine with a walk through the nearby Klewer Market for batik shopping."]'::jsonb,
    '["Visit on Saturday morning for the best cultural performances at the palace.","Hire a guide — the stories behind the artifacts are fascinating.","Don''t miss the museum''s keris (ceremonial dagger) collection.","Combine with a walk through the nearby Klewer Market for batik shopping."]'::jsonb,
    'Tuesday to Sunday mornings for the full palace experience',
    'Tuesday to Sunday mornings for the full palace experience',
    '{"temp":"30°C","condition":"Sunny","status":"Warm day — perfect for exploring the palace and Solo''s heritage streets."}'::jsonb,
    -7.5733, 110.8267,
    '[{"id":"r1","userName":"Sophia Laurent","userAvatar":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150","rating":5,"date":"2026-07-01","comment":"The palace is a living museum. The gamelan performance gave me chills — such a rich cultural experience."}]'::jsonb,
    '[{"id":"ks-p1","name":"The Royal Surakarta Heritage Hotel","category":"hotel","image":"https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=600","rating":4.7,"price":"IDR 900,000 / night","distance":"1.5 km","description":"Luxury heritage hotel in the heart of Solo, walking distance from the Keraton.","address":"Jl. Slamet Riyadi, Surakarta"}]'::jsonb,
    '[{"q":"Is it still an active palace?","a":"Yes, the Susuhunan and his family reside in parts of the complex."},{"q":"What is the dress code?","a":"Modest clothing is required. Sarongs are available at the entrance."}]'::jsonb,
    'published'
),

-- 22. BENTENG PENDEM (Cilacap)
(
    'bentengpendem',
    'Benteng Pendem', 'Benteng Pendem',
    'The Hidden Dutch Fortress on Turtle Bay', 'The Hidden Dutch Fortress on Turtle Bay',
    'heritage', 'Cilacap, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1584892077118-6399f5a200e5?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1566559631133-969041fc5583?do=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.4, 900,
    'Benteng Pendem (The Sunken Fortress) is a Dutch colonial coastal fortress built between 1861 and 1879 on Teluk Penyu (Turtle Bay) in Cilacap. Designed to defend the strategic port from naval attacks, the fort is built low into the ground — hence its name — with thick coral-stone walls, underground tunnels, cannons, and a moat.',
    'Benteng Pendem (The Sunken Fortress) is a Dutch colonial coastal fortress built between 1861 and 1879 on Teluk Penyu (Turtle Bay) in Cilacap. Designed to defend the strategic port from naval attacks, the fort is built low into the ground — hence its name — with thick coral-stone walls, underground tunnels, cannons, and a moat.',
    'Built by the Dutch East Indies government during the Aceh War period, Benteng Pendem was part of a coastal defense network. The fort appears ''sunken'' because it was built at sea level with only the roof visible from the ocean, making it a difficult target for enemy ships. After Indonesian independence, it was used as a military barracks and later opened as a heritage site.',
    'Built by the Dutch East Indies government during the Aceh War period, Benteng Pendem was part of a coastal defense network. The fort appears ''sunken'' because it was built at sea level with only the roof visible from the ocean, making it a difficult target for enemy ships. After Indonesian independence, it was used as a military barracks and later opened as a heritage site.',
    'IDR 15,000 (Adult) / IDR 10,000 (Child)',
    '08:00 AM – 05:00 PM Daily',
    '["Underground Tunnels","Historical Cannon Displays","Dutch Barracks","Coastal Viewing Platform","Small Museum","Parking Area","Food Stalls","Restrooms"]'::jsonb,
    '["Underground Tunnels","Historical Cannon Displays","Dutch Barracks","Coastal Viewing Platform","Small Museum","Parking Area","Food Stalls","Restrooms"]'::jsonb,
    '["Wear a flashlight or use your phone — the underground tunnels are dark.","Hire a guide at the entrance for the best historical context.","Combine with a visit to Teluk Penyu beach right next door.","The fort looks best in golden hour light (late afternoon)."]'::jsonb,
    '["Wear a flashlight or use your phone — the underground tunnels are dark.","Hire a guide at the entrance for the best historical context.","Combine with a visit to Teluk Penyu beach right next door.","The fort looks best in golden hour light (late afternoon)."]'::jsonb,
    'May to October (Dry Season); late afternoon for good light',
    'May to October (Dry Season); late afternoon for good light',
    '{"temp":"30°C","condition":"Sunny with Sea Breeze","status":"Good conditions for exploring the fort and nearby beach."}'::jsonb,
    -7.7410, 109.0140,
    '[{"id":"r1","userName":"Budi Santoso","userAvatar":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150","rating":4.5,"date":"2026-07-15","comment":"Exploring the underground tunnels and seeing the old Dutch cannons was fascinating. Great history lesson."}]'::jsonb,
    '[{"id":"bp-p1","name":"Cilacap Seaside Inn","category":"hotel","image":"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=600","rating":4.2,"price":"IDR 350,000 / night","distance":"2 km","description":"Budget-friendly inn steps from Teluk Penyu beach.","address":"Jl. Benteng Pendem, Cilacap"}]'::jsonb,
    '[{"q":"How long does the tour take?","a":"About 1 hour for a full exploration of the fort and tunnels."},{"q":"Are the tunnels safe?","a":"Yes, they are well-maintained with some lighting. Watch your step."}]'::jsonb,
    'published'
),

-- 23. TELUK PENYU BEACH (Cilacap)
(
    'telukpenyu',
    'Teluk Penyu Beach', 'Teluk Penyu Beach',
    'Turtle Bay — Where History Meets the Ocean', 'Turtle Bay — Where History Meets the Ocean',
    'nature', 'Cilacap, Central Java', 'Near Yogyakarta',
    '["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    4.4, 1700,
    'Teluk Penyu (Turtle Bay) is Cilacap''s main beach, known for its golden sand, calm waters, and iconic views of Nusakambangan Island across the bay. The beach promenade is lined with food stalls, and the adjacent Benteng Pendem fortress adds a unique historical dimension to the coastal experience.',
    'Teluk Penyu (Turtle Bay) is Cilacap''s main beach, known for its golden sand, calm waters, and iconic views of Nusakambangan Island across the bay. The beach promenade is lined with food stalls, and the adjacent Benteng Pendem fortress adds a unique historical dimension to the coastal experience.',
    'Named after the sea turtles that once nested abundantly on its shores, Teluk Penyu has been a strategic anchorage since the Dutch colonial era. The bay is sheltered by Nusakambangan Island, creating calm waters perfect for recreation. The beach underwent major revitalization in 2015, transforming it into a modern public space while preserving its natural charm.',
    'Named after the sea turtles that once nested abundantly on its shores, Teluk Penyu has been a strategic anchorage since the Dutch colonial era. The bay is sheltered by Nusakambangan Island, creating calm waters perfect for recreation. The beach underwent major revitalization in 2015, transforming it into a modern public space while preserving its natural charm.',
    'IDR 10,000 / person',
    '06:00 AM – 06:00 PM Daily',
    '["Golden Sand Beach","Beach Promenade","Children''s Playground","Food Stalls & Warungs","Benteng Pendem Adjacent","Parking Area","Restrooms","Musholla"]'::jsonb,
    '["Golden Sand Beach","Beach Promenade","Children''s Playground","Food Stalls & Warungs","Benteng Pendem Adjacent","Parking Area","Restrooms","Musholla"]'::jsonb,
    '["Visit late afternoon for sunset over Nusakambangan Island.","Try the fresh seafood at the beachside warungs.","Combine with Benteng Pendem for a full day of history and beach.","The water is calm and safe for swimming."]'::jsonb,
    '["Visit late afternoon for sunset over Nusakambangan Island.","Try the fresh seafood at the beachside warungs.","Combine with Benteng Pendem for a full day of history and beach.","The water is calm and safe for swimming."]'::jsonb,
    'May to September (Dry Season); late afternoon for sunset',
    'May to September (Dry Season); late afternoon for sunset',
    '{"temp":"30°C","condition":"Sunny with Sea Breeze","status":"Beautiful beach weather — calm waters and sunny skies."}'::jsonb,
    -7.7430, 109.0120,
    '[{"id":"r1","userName":"Yuki Tanaka","userAvatar":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150","rating":4.0,"date":"2026-06-25","comment":"Clean beach with nice views of Nusakambangan. The seafood stalls are excellent!"}]'::jsonb,
    '[{"id":"tp-p1","name":"Teluk Penyu Seafood Plaza","category":"restaurant","image":"https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=600","rating":4.3,"price":"IDR 30,000 – 80,000 / person","distance":"On-Site","description":"Beachfront seafood market with fresh catch grilled to order.","address":"Teluk Penyu Beach, Cilacap"}]'::jsonb,
    '[{"q":"Is it safe to swim?","a":"Yes, the bay is calm and protected by Nusakambangan Island."},{"q":"Are turtles still visible?","a":"Sightings are rare now, but the beach is named after them."}]'::jsonb,
    'published'
)
ON CONFLICT (external_id) DO NOTHING;
