package seeds

import (
	"fmt"
	"log"
	"time"

	"pleco-api/internal/modules/event"

	"gorm.io/gorm"
)

func SeedEvents(db *gorm.DB) {
	mustHaveDB(db)

	events := []event.Event{
		{
			ExternalID:   "bakpia-trail-festival",
			Title:        "Bakpia Trail Festival",
			Description:  "Bakpia Trail Festival adalah perayaan kuliner dan budaya yang menyoroti kelezatan bakpia, camilan legendaris Yogyakarta. Nikmati lokakarya memasak, sesi mencicipi, pasar makanan, dan pertunjukan budaya yang menampilkan tradisi lokal.\n\nAcara ini menggabungkan cita rasa, kreativitas, dan warisan dalam satu pengalaman yang tak terlupakan.",
			Location:     "Pathuk, Yogyakarta",
			StartDate:    "2026-08-15",
			EndDate:      "2026-08-16",
			ImageURL:     "https://commons.wikimedia.org/wiki/Special:FilePath/Bakpia%20pathuk.jpg",
			Category:     "Food Festival",
			Status:       "",
			Latitude:     -7.8024,
			Longitude:    110.3649,
			MaxAttendees: 2000,
			TicketPrice:  "IDR 100,000",
			Organizer:    "Yogyakarta Culinary Board",
			Highlights:   event.JSONArr{"Bakpia Cooking Workshop", "Street Food Market", "Cultural Performances"},
		},
		{
			ExternalID:    "sekaten-2026",
			DestinationID: "keraton",
			Title:         "Sekaten Yogyakarta 2026",
			Description:  "Sekaten adalah festival budaya tahunan yang merayakan kelahiran Nabi Muhammad SAW. Festival ini menampilkan gamelan kerajaan, pasar malam, dan berbagai pertunjukan seni tradisional Jawa di sekitar Alun-Alun Utara Keraton Yogyakarta.",
			Location:     "Alun-Alun Utara, Yogyakarta",
			StartDate:    "2026-09-01",
			EndDate:      "2026-09-07",
			ImageURL:     "https://upload.wikimedia.org/wikipedia/commons/c/c9/Gunungan_darat_during_Garebeg_Mulud_Yogyakarta_Dec_2017_Pj_IMG_4517sm.jpg",
			Category:     "Cultural Festival",
			Status:       "",
			Latitude:     -7.8052,
			Longitude:    110.3647,
			MaxAttendees: 10000,
			TicketPrice:  "Gratis",
			Organizer:    "Keraton Yogyakarta",
			Highlights:   event.JSONArr{"Gamelan Kerajaan", "Pasar Malam Sekaten", "Gunungan Grebeg", "Pertunjukan Wayang"},
		},
		{
			ExternalID:    "prambanan-jazz-2026",
			DestinationID: "prambanan",
			Title:         "Prambanan Jazz Festival 2026",
			Description:  "Prambanan Jazz Festival adalah salah satu festival musik paling ikonik di Indonesia. Digelar di depan latar belakang megah Candi Prambanan yang diterangi cahaya, festival ini menghadirkan musisi jazz terbaik dari Indonesia dan dunia.",
			Location:     "Kompleks Candi Prambanan, Sleman",
			StartDate:    "2026-07-18",
			EndDate:      "2026-07-20",
			ImageURL:     "https://upload.wikimedia.org/wikipedia/commons/4/4f/Prambananjazz-6-2020.png",
			Category:     "Music Festival",
			Status:       "",
			Latitude:     -7.7520,
			Longitude:    110.4914,
			MaxAttendees: 5000,
			TicketPrice:  "IDR 350,000",
			Organizer:    "Rajawali Indonesia",
			Highlights:   event.JSONArr{"Live Jazz Performance", "Sunset Concert", "Heritage Stage", "Culinary Village"},
		},
		{
			ExternalID:    "merapi-adventure-race",
			DestinationID: "merapi",
			Title:         "Merapi Adventure Race 2026",
			Description:  "Tantang dirimu dalam kompetisi petualangan multi-disiplin melintasi medan vulkanik Gunung Merapi. Termasuk trail running, mountain biking, dan navigasi rute. Cocok untuk petualang sejati yang ingin merasakan thrill Merapi.",
			Location:     "Lereng Merapi, Sleman",
			StartDate:    "2026-08-22",
			EndDate:      "2026-08-23",
			ImageURL:     "https://commons.wikimedia.org/wiki/Special:FilePath/Merapi%2C_Yogyakarta.jpg",
			Category:     "Adventure",
			Status:       "",
			Latitude:     -7.5407,
			Longitude:    110.4457,
			MaxAttendees: 500,
			TicketPrice:  "IDR 250,000",
			Organizer:    "Merapi Volcano Trail Community",
			Highlights:   event.JSONArr{"Trail Running 42km", "Mountain Biking", "Volcanic Landscape Views", "Night Navigation"},
		},
		{
			ExternalID:   "jogja-fashion-week",
			Title:        "Jogja Fashion Week 2026",
			Description:  "Pekan mode bergengsi yang menampilkan koleksi terbaru dari desainer lokal dan nasional dengan sentuhan batik dan tenun tradisional Yogyakarta. Merayakan kekayaan tekstil Jawa dalam balutan mode kontemporer.",
			Location:     "Jogja Expo Center, Yogyakarta",
			StartDate:    "2026-10-10",
			EndDate:      "2026-10-13",
			ImageURL:     "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1600&q=80",
			Category:     "Fashion & Art",
			Status:       "",
			Latitude:     -7.8226,
			Longitude:    110.4107,
			MaxAttendees: 3000,
			TicketPrice:  "IDR 75,000",
			Organizer:    "Dinas Pariwisata DIY",
			Highlights:   event.JSONArr{"Batik Runway Show", "Traditional Weaving Exhibition", "Designer Meet & Greet", "Craft Market"},
		},
		{
			ExternalID:    "parangtritis-kite-festival",
			DestinationID: "parangtritis",
			Title:         "Parangtritis International Kite Festival",
			Description:  "Festival layang-layang internasional yang digelar di pantai ikonik Parangtritis. Ratusan layang-layang raksasa dari berbagai negara menghiasi langit pantai selatan Yogyakarta. Pertunjukan terbaik saat angin laut berhembus kencang.",
			Location:     "Pantai Parangtritis, Bantul",
			StartDate:    "2026-09-19",
			EndDate:      "2026-09-21",
			ImageURL:     "https://images.unsplash.com/photo-1530870110042-98b2cb110834?auto=format&fit=crop&w=1600&q=80",
			Category:     "Cultural Festival",
			Status:       "",
			Latitude:     -8.0257,
			Longitude:    110.3318,
			MaxAttendees: 8000,
			TicketPrice:  "Gratis",
			Organizer:    "Dinas Pariwisata Bantul",
			Highlights:   event.JSONArr{"International Kite Competition", "Night Kite Show", "Beach Sunset View", "Cultural Performance"},
		},
		{
			ExternalID:   "upacara-adat-saparan-bekakak",
			Title:        "Upacara Adat Saparan Bekakak",
			Description:  "Kirab tahunan warga Gamping menyembelih tiruan sepasang pengantin dari ketan berisi kuah gula mawar merah sebagai lambang tolak bala kuno peninggalan Kraton.",
			Location:     "Gunung Gamping, Ambarketawang, Gamping, Sleman",
			StartDate:    "2026-10-01",
			EndDate:      "2026-10-01",
			ImageURL:     "https://upload.wikimedia.org/wikipedia/commons/c/c9/Gunungan_darat_during_Garebeg_Mulud_Yogyakarta_Dec_2017_Pj_IMG_4517sm.jpg",
			Category:     "Cultural Ceremony",
			Status:       "",
			Latitude:     -7.8032,
			Longitude:    110.3212,
			MaxAttendees: 3000,
			TicketPrice:  "Gratis",
			Organizer:    "Keraton Yogyakarta",
			Highlights:   event.JSONArr{"Kirab Adat", "Gunungan Ketan", "Pertunjukan Budaya", "Ritual Tolak Bala"},
		},
		{
			ExternalID:   "upacara-rebo-pungkasan",
			Title:        "Upacara Rebo Pungkasan",
			Description:  "Kirab gunungan lemper raksasa menyambut hari Rabu terakhir bulan Sapar, penanda warisan syukur warga Bantul peninggalan Kyai Wiroyudo pangeran kraton.",
			Location:     "Wonokromo, Pleret, Bantul",
			StartDate:    "2026-11-01",
			EndDate:      "2026-11-01",
			ImageURL:     "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1600&q=80",
			Category:     "Cultural Ceremony",
			Status:       "",
			Latitude:     -7.8715,
			Longitude:    110.3951,
			MaxAttendees: 5000,
			TicketPrice:  "Gratis",
			Organizer:    "Pemkab Bantul",
			Highlights:   event.JSONArr{"Gunungan Lemper Raksasa", "Kirab Warga", "Ritual Saparan", "Pasar Rakyat"},
		},
		{
			ExternalID:    "sendratari-roro-jonggrang",
			DestinationID: "prambanan",
			Title:         "Sendratari Roro Jonggrang Prambanan",
			Description:  "Pementasan seni drama tari legendaris kisah berdirinya seribu candi Roro Jonggrang dan Bandung Bondowoso. Digelar megah di panggung terbuka Candi Prambanan dengan tata pencahayaan modern dramatis dan efek multimedia yang memukau serta latar tiga candi utama.",
			Location:     "Kompleks Candi Prambanan, Sleman",
			StartDate:    "2026-07-01",
			EndDate:      "2026-10-31",
			ImageURL:     "https://commons.wikimedia.org/wiki/Special:FilePath/Ramayana_Prambanan_3.jpg",
			Category:     "Cultural Performance",
			Status:       "",
			Latitude:     -7.7520,
			Longitude:    110.4915,
			MaxAttendees: 3000,
			TicketPrice:  "Mulai Rp 50.000",
			Organizer:    "PT Taman Wisata Candi Prambanan",
			Highlights:   event.JSONArr{"Drama Tari Legendaris", "Tata Cahaya Modern", "Latar Candi Prambanan", "Gamelan Langsung"},
		},
		{
			ExternalID:   "ngayogjazz",
			Title:        "Ngayogjazz",
			Description:  "Festival musik jazz tahunan unik berskala internasional yang sengaja digelar di pedesaan (desa wisata) sekitar Yogyakarta. Mengusung konsep merakyat Jazz Mawi Sangu Pari, memadukan keahlian musisi jazz dunia dengan kehangatan ramah tamah warga desa dan kuliner lokal.",
			Location:     "Desa Wisata Pilihan (Berpindah Setiap Tahun di Jogja)",
			StartDate:    "2026-11-14",
			EndDate:      "2026-11-16",
			ImageURL:     "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1600&q=80",
			Category:     "Music Festival",
			Status:       "",
			Latitude:     -7.6852,
			Longitude:    110.3541,
			MaxAttendees: 5000,
			TicketPrice:  "Gratis (Cukup Bayar Parkir Desa)",
			Organizer:    "Ngayogjazz Committee",
			Highlights:   event.JSONArr{"Jazz di Pedesaan", "Kuliner Lokal Desa", "Panggung Terbuka", "Interaksi Warga Desa"},
		},
		{
			ExternalID:    "seloso-wage-malioboro",
			DestinationID: "malioboro",
			Title:         "Seloso Wage Malioboro",
			Description:  "Hari bebas kendaraan bermotor di sepanjang koridor Jalan Malioboro yang jatuh setiap hari Selasa Wage dalam penanggalan Jawa. Menjadi panggung seni jalanan raksasa di mana ratusan musisi, penari tradisi, badut, dan teater jalanan Jogja tampil estetik menghibur publik.",
			Location:     "Sepanjang Jalan Malioboro, Kota Yogyakarta",
			StartDate:    "2026-07-01",
			EndDate:      "2026-12-31",
			ImageURL:     "https://images.unsplash.com/photo-1543874768-af0b9c4090d5?auto=format&fit=crop&w=1600&q=80",
			Category:     "Street Festival",
			Status:       "",
			Latitude:     -7.7942,
			Longitude:    110.3656,
			MaxAttendees: 10000,
			TicketPrice:  "Gratis",
			Organizer:    "Pemkot Yogyakarta",
			Highlights:   event.JSONArr{"Seni Jalanan", "Musisi Lokal", "Teater Jalanan", "Pasar Rakyat Malioboro"},
		},
		{
			ExternalID:   "kustomfest",
			Title:        "Kustomfest (Indonesia Kustom Kulture Show)",
			Description:  "Festival kustom kulture terbesar di Indonesia yang mempertemukan para modifikator motor, mobil, seniman tato, serta pameran seni retro dunia. Sangat viral di kalangan pecinta otomotif nasional dan global karena menampilkan karya kustom tingkat tinggi nan presisi.",
			Location:     "Jogja Expo Center (JEC), Banguntapan, Bantul",
			StartDate:    "2026-10-03",
			EndDate:      "2026-10-05",
			ImageURL:     "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1600&q=80",
			Category:     "Custom Culture",
			Status:       "",
			Latitude:     -7.8042,
			Longitude:    110.4005,
			MaxAttendees: 15000,
			TicketPrice:  "Mulai Rp 60.000",
			Organizer:    "Kustomfest Foundation",
			Highlights:   event.JSONArr{"Custom Motorcycle Show", "Tattoo Convention", "Retro Art Exhibition", "Live Music"},
		},
		{
			ExternalID:    "bioskop-sonobudoyo",
			DestinationID: "museum-sonobudoyo",
			Title:         "Bioskop Sonobudoyo",
			Description:  "Pemutaran bioskop alternatif gratis di dalam kompleks Museum Sonobudoyo yang memutarkan berbagai film dokumenter budaya, film pendek karya sineas lokal Jogja, dan sejarah klasik Nusantara. Mengusung bioskop vintage modern mini dengan kualitas audio visual bioskop komersial.",
			Location:     "Gedung Bioskop Museum Sonobudoyo, Kota Yogyakarta",
			StartDate:    "2026-07-01",
			EndDate:      "2026-12-31",
			ImageURL:     "https://upload.wikimedia.org/wikipedia/commons/9/9b/SanabudayaMuseumEntrySign85.jpg",
			Category:     "Film & Cinema",
			Status:       "",
			Latitude:     -7.8025,
			Longitude:    110.3635,
			MaxAttendees: 100,
			TicketPrice:  "Gratis (Wajib Reservasi Online)",
			Organizer:    "Museum Sonobudoyo",
			Highlights:   event.JSONArr{"Film Dokumenter Budaya", "Film Pendek Sineas Lokal", "Bioskop Vintage", "Diskusi Seni"},
		},
		{
			ExternalID:    "sendratari-ramayana-prambanan",
			DestinationID: "prambanan",
			Title:         "Sendratari Ramayana Prambanan",
			Description:  "Seni pertunjukan tari teater paling spektakuler dan legendaris di Indonesia yang mementaskan kisah kepahlawanan Rama menyelamatkan Shinta. Ditampilkan tanpa dialog, mengandalkan ekspresi gerak tari Jawa indah, gamelan rancak, dan latar belakang megah tiga candi utama Prambanan yang bersinar keemasan.",
			Location:     "Panggung Terbuka Candi Prambanan, Sleman",
			StartDate:    "2026-05-01",
			EndDate:      "2026-10-31",
			ImageURL:     "https://commons.wikimedia.org/wiki/Special:FilePath/Ramayana_Prambanan_3.jpg",
			Category:     "Cultural Performance",
			Status:       "",
			Latitude:     -7.7512,
			Longitude:    110.4901,
			MaxAttendees: 3000,
			TicketPrice:  "Mulai Rp 150.000",
			Organizer:    "PT Taman Wisata Candi Prambanan",
			Highlights:   event.JSONArr{"Tari Teater Tanpa Dialog", "Latar Candi Prambanan", "Gamelan Tradisional", "Kisah Rama-Shinta"},
		},
		{
			ExternalID:   "yogyakarta-gamelan-festival",
			Title:        "Yogyakarta Gamelan Festival (YGF)",
			Description:  "Gathering seni gamelan internasional legendaris yang mempertemukan para pemain, pencipta, dan pecinta gamelan dari seluruh penjuru dunia. Menyajikan pementasan gamelan kontemporer radikal hingga klasik purba yang sangat viral mendunia.",
			Location:     "Gedung TBY atau Pendopo Heritage di Yogyakarta",
			StartDate:    "2026-09-05",
			EndDate:      "2026-09-08",
			ImageURL:     "https://commons.wikimedia.org/wiki/Special:FilePath/Sarons_of_Gamelan_Sekati,_Yogyakarta.jpg",
			Category:     "Music Festival",
			Status:       "",
			Latitude:     -7.8005,
			Longitude:    110.3685,
			MaxAttendees: 2000,
			TicketPrice:  "Gratis (Sebagian Berbayar)",
			Organizer:    "YGF Foundation",
			Highlights:   event.JSONArr{"Gamelan Internasional", "Workshop Gamelan", "Pertunjukan Kolosal", "Pertemuan Seniman Dunia"},
		},
		{
			ExternalID:    "jogja-international-street-performance",
			DestinationID: "malioboro",
			Title:         "Jogja International Street Performance (JISP)",
			Description:  "Festival tari jalanan berskala internasional yang membawa panggung seni keluar dari gedung teater menuju ruang publik terbuka di Yogyakarta. Ratusan seniman tari jalanan mancanegara menampilkan ekspresi gerak tubuh kreatif interaktif di hadapan publik Malioboro.",
			Location:     "Jalan Malioboro dan Titik Nol Kilometer, Kota Yogyakarta",
			StartDate:    "2026-10-20",
			EndDate:      "2026-10-22",
			ImageURL:     "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1600&q=80",
			Category:     "Street Performance",
			Status:       "",
			Latitude:     -7.8012,
			Longitude:    110.3648,
			MaxAttendees: 8000,
			TicketPrice:  "Gratis",
			Organizer:    "Dinas Pariwisata DIY",
			Highlights:   event.JSONArr{"Tari Jalanan Internasional", "Seniman Mancanegara", "Interaktif Publik", "Panggung Terbuka Malioboro"},
		},
		{
			ExternalID:    "sandyakala-jonggrang",
			DestinationID: "ratuboko",
			Title:         "Sandyakala Jonggrang",
			Description:  "Pertunjukan seni budaya magis yang menghidupkan legenda Roro Jonggrang di tengah megahnya Keraton Ratu Boko. Dimulai saat senja pukul 17.00 WIB, perpaduan tarian tradisional, gamelan, dan latar sunset yang memukau menciptakan pengalaman budaya yang tak terlupakan. Diselenggarakan oleh PT Taman Wisata Candi Borobudur, Prambanan, dan Ratu Boko.",
			Location:     "Keraton Ratu Boko, Sleman",
			StartDate:    "2026-06-21",
			EndDate:      "2026-07-03",
			ImageURL:     "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1600&q=80",
			Category:     "Cultural Performance",
			Status:       "",
			Latitude:     -7.7700,
			Longitude:    110.4880,
			MaxAttendees: 2000,
			TicketPrice:  "Gratis (dengan tiket masuk Ratu Boko Rp40.000)",
			Organizer:    "PT Taman Wisata Candi Borobudur, Prambanan, dan Ratu Boko",
			Highlights:   event.JSONArr{"Tarian Roro Jonggrang", "Sunset di Ratu Boko", "Gamelan Tradisional", "Pertunjukan Senja"},
		},
		{
			ExternalID:    "centili-obelix-hills",
			DestinationID: "obelix-hills",
			Title:         "Centili Dance Group di Obelix Hills",
			Description:  "Centili Dance Group adalah grup tari komedi yang sangat populer di Yogyakarta. Menyajikan pertunjukan tari unik yang memadukan unsur komedi, kostum nyentrik, dan gerakan akrobatik. Para penari pria sering memerankan karakter wanita dengan gaya energik dan menghibur. Tampil setiap hari Sabtu di Obelix Hills Prambanan mulai pukul 16.00 WIB.",
			Location:     "Obelix Hills, Klumprit, Prambanan, Sleman",
			StartDate:    "2026-07-13",
			EndDate:      "2026-07-13",
			ImageURL:     "https://images.unsplash.com/photo-1545156521-77bd85671d30?auto=format&fit=crop&w=1600&q=80",
			Category:     "Dance & Comedy",
			Status:       "",
			Latitude:     -7.7612,
			Longitude:    110.5063,
			MaxAttendees: 500,
			TicketPrice:  "Gratis (dengan tiket masuk Obelix Hills Rp20.000-Rp25.000)",
			Organizer:    "Obelix Hills Management",
			Highlights:   event.JSONArr{"Tari Komedi", "Kostum Nyentrik", "Akrobatik", "Hiburan Keluarga"},
		},
		{
			ExternalID:    "centili-obelix-sea-view",
			DestinationID: "obelix-sea-view",
			Title:         "Centili Dance Group di Obelix Sea View",
			Description:  "Centili Dance Group adalah grup tari komedi yang sangat populer di Yogyakarta. Menyajikan pertunjukan tari unik yang memadukan unsur komedi, kostum nyentrik, dan gerakan akrobatik. Para penari pria sering memerankan karakter wanita dengan gaya energik dan menghibur. Tampil rutin di Obelix Sea View Gunungkidul pada pukul 17.00 WIB. Cek jadwal terbaru di Instagram @obelixseaview.",
			Location:     "Obelix Sea View, Giricahyo, Purwosari, Gunungkidul",
			StartDate:    "2026-07-01",
			EndDate:      "2026-07-31",
			ImageURL:     "https://images.unsplash.com/photo-1545156521-77bd85671d30?auto=format&fit=crop&w=1600&q=80",
			Category:     "Dance & Comedy",
			Status:       "",
			Latitude:     -8.0285,
			Longitude:    110.3325,
			MaxAttendees: 800,
			TicketPrice:  "Gratis (dengan tiket masuk Obelix Sea View Rp30.000-Rp50.000)",
			Organizer:    "Obelix Sea View Management",
			Highlights:   event.JSONArr{"Tari Komedi", "Kostum Nyentrik", "Akrobatik", "Hiburan Keluarga"},
		},
		{
			ExternalID:   "3rd-borobudur-international-conference",
			DestinationID: "borobudur",
			Title:        "3rd Borobudur International Conference",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20180423-WA0000-724x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "abhiseka-candi-prambanan",
			DestinationID: "prambanan",
			Title:        "Abhiseka Candi Prambanan",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "air-cabang-lohi",
			DestinationID: "air-cabang-lohi",
			Title:        "Air Cabang Lohi",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "air-santok",
			DestinationID: "air-santok",
			Title:        "Air Santok",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "air-terjun-simpang-dingin",
			DestinationID: "air-terjun-simpang-dingin",
			Title:        "Air Terjun Simpang Dingin",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "air-wertuleli",
			DestinationID: "air-wertuleli",
			Title:        "Air Wertuleli",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "alam-dan-religi-gunung-taruwongso",
			DestinationID: "alam-dan-religi-gunung-taruwongso",
			Title:        "Alam dan Religi Gunung Taruwongso",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "alam-desa-saluassing",
			DestinationID: "alam-desa-saluassing",
			Title:        "Alam Desa Saluassing",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "alam-lestari",
			DestinationID: "alam-lestari",
			Title:        "ALAM LESTARI",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "alam-mangrove-taat",
			DestinationID: "alam-mangrove-taat",
			Title:        "Alam Mangrove Taat",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "astana-gede",
			DestinationID: "astana-gede",
			Title:        "Astana Gede",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "baho-beach",
			DestinationID: "baho-beach",
			Title:        "Baho Beach",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "bakbakan",
			DestinationID: "bakbakan",
			Title:        "Bakbakan",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "balai-sawala",
			DestinationID: "balai-sawala",
			Title:        "Balai Sawala",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "balang-butung",
			DestinationID: "balang-butung",
			Title:        "Balang Butung",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "balocci-baru",
			DestinationID: "balocci-baru",
			Title:        "Balocci Baru",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "banjoe-adji",
			DestinationID: "banjoe-adji",
			Title:        "Banjoe Adji",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "batik-musik-festival",
			Title:        "Batik Musik Festival",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20190910-WA0048-1024x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "bhumi-nawasena",
			DestinationID: "bhumi-nawasena",
			Title:        "Bhumi Nawasena",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-andamp-prambanan-water-color-heritage-exhibition",
			DestinationID: "borobudur",
			Title:        "Borobudur &amp; Prambanan Water Color Heritage Exhibition",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Haritage-Art-1-761x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-cultural-feast",
			DestinationID: "borobudur",
			Title:        "Borobudur Cultural Feast",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/BOROBUDUR-CULTURAL-FEAST-1024x730-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-cultural-feast-2017",
			DestinationID: "borobudur",
			Title:        "Borobudur Cultural Feast 2017",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20171206-WA0021-723x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-international-10k",
			DestinationID: "borobudur",
			Title:        "Borobudur International 10K",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/18-1024x802-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-international-conference",
			DestinationID: "borobudur",
			Title:        "Borobudur International Conference",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/BoroInternConf_only_IDe-724x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-international-festival",
			DestinationID: "borobudur",
			Title:        "Borobudur International Festival",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/7-739x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-lego-festival",
			DestinationID: "borobudur",
			Title:        "Borobudur Lego Festival",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Lego-Festival-Revisi-722x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-legoland-festival",
			DestinationID: "borobudur",
			Title:        "Borobudur Legoland Festival",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Borobudur-Legoland-Festival-3-880x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-marathon",
			DestinationID: "borobudur",
			Title:        "Borobudur Marathon",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/23632418_1759670507408488_1883060852641535289_o-1024x576-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-music-performance",
			DestinationID: "borobudur",
			Title:        "Borobudur Music Performance",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/15-783x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-nite-2017",
			DestinationID: "borobudur",
			Title:        "Borobudur Nite 2017",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/19-970x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-nite-2018",
			DestinationID: "borobudur",
			Title:        "Borobudur Nite 2018",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20181217-WA0028.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-nite-2019",
			DestinationID: "borobudur",
			Title:        "Borobudur Nite 2019",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Borobudur-Nite-2019-576x1024-1.jpeg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-photo-contest",
			DestinationID: "borobudur",
			Title:        "Borobudur Photo Contest",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/5.1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-photo-contest-2017",
			DestinationID: "borobudur",
			Title:        "BOROBUDUR PHOTO CONTEST 2017",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/FA_Poster_lombafoto_hires-01-724x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "borobudur-symphony",
			DestinationID: "borobudur",
			Title:        "Borobudur Symphony",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Iklan-Dagi-1-1024x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "bri-prioritas-mahakarya-borobudur-2018",
			DestinationID: "borobudur",
			Title:        "BRI Prioritas Mahakarya Borobudur 2018",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/flyer_mahakarya-722x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "budaya",
			DestinationID: "budaya",
			Title:        "budaya",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "budaya-tenun",
			DestinationID: "budaya-tenun",
			Title:        "Budaya Tenun",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "bukit-perrak",
			DestinationID: "bukit-perrak",
			Title:        "Bukit Perrak",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "bukit-salak",
			DestinationID: "bukit-salak",
			Title:        "BUKIT SALAK",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "buluh-awar",
			DestinationID: "buluh-awar",
			Title:        "Buluh Awar",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "bulukerto",
			DestinationID: "bulukerto",
			Title:        "BULUKERTO",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
			VideoURL:     "https://www.youtube.com/watch?v=dAItDS8AO1Y",
		},
		{
			ExternalID:   "buyung-buyung",
			DestinationID: "buyung-buyung",
			Title:        "BUYUNG-BUYUNG",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "candigaron",
			DestinationID: "candigaron",
			Title:        "CANDIGARON",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "danau-uter-biru",
			DestinationID: "danau-uter-biru",
			Title:        "Danau Uter Biru",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "dramatari-legenda-roro-jonggrang",
			Title:        "Dramatari Legenda Roro Jonggrang",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/COE-2-NEW-SAVE_resize.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "exclusive-performance-ramayana-ballet-prambanan",
			DestinationID: "ramayana",
			Title:        "Exclusive Performance Ramayana Ballet Prambanan",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Special-Performance-Ramayana-Ballet-Prambanan-with-KJRI-Mumbai-and-KBRI-India.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "festival-gamelan-andamp-langen-cerita",
			Title:        "Festival Gamelan &amp; Langen Cerita",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/13-702x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "festival-keris-ratu-boko",
			DestinationID: "ratu-boko",
			Title:        "Festival Keris Ratu Boko",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/FESTIVAL-KERIS-1_C-865x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "festival-payung-indonesia-2019",
			Title:        "Festival Payung Indonesia 2019",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/POSTER-876x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "festival-payung-indonesia-2020",
			Title:        "Festival Payung Indonesia 2020",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/FESPIN-2020_b-676x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "festival-tari-keraton",
			Title:        "Festival Tari Keraton",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/10-728x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "festival-yoga-internasional",
			Title:        "Festival Yoga Internasional",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/DJI_0099-1024x576-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "hargomulyo",
			DestinationID: "hargomulyo",
			Title:        "Hargomulyo",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "hari-raya-kebudayaan-borobudur",
			DestinationID: "borobudur",
			Title:        "Hari Raya Kebudayaan Borobudur",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/16-1024x833-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "hari-raya-waisak",
			Title:        "Hari Raya Waisak",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Waisak-Borobudur-750x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "heritage-bersama-tni",
			Title:        "Heritage Bersama TNI",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/heritage-TNI-1024x864-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "international-world-heritage-conference",
			Title:        "International World Heritage Conference",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/INTERNATIONAL-WORLD-HERITAGE-1024x660-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "jadwal-pentas-legenda-roro-jonggrang-2023",
			Title:        "Jadwal Pentas Legenda Roro Jonggrang 2023",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/brosur-roro-jonggrang-2023-979x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "jadwal-pentas-sendratari-ramayana-2025",
			DestinationID: "ramayana",
			Title:        "Jadwal Pentas Sendratari Ramayana 2025",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/COE-1-NEW-SAVE_resize-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "jogja-international-heritage-walk",
			Title:        "Jogja International Heritage Walk",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/17-978x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "ledoknongko",
			DestinationID: "ledoknongko",
			Title:        "Ledoknongko",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "legenda-roro-jonggrang-kalender-event-2020-2021",
			Title:        "Legenda Roro Jonggrang: Kalender Event 2020 – 2021",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/WhatsApp-Image-2020-12-17-at-1.10.27-PM-1024x1024-1.jpeg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "lomba-cipta-kreasi-tari-borobudur",
			DestinationID: "borobudur",
			Title:        "Lomba Cipta Kreasi Tari Borobudur",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Cipta-Kreasi-Tari-Borobudur-1-787x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "mahakarya-borobudur-hair-style-andamp-fashion",
			DestinationID: "borobudur",
			Title:        "Mahakarya Borobudur Hair Style &amp; Fashion",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Mahakarya-Bdr-1-718x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "malam-budaya-pengerupukan",
			DestinationID: "budaya",
			Title:        "Malam Budaya Pengerupukan",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20180317-WA0003-1024x682-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "mandiri-jogja-international-marathon",
			Title:        "Mandiri Jogja International Marathon",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Mandiri-Jogja-International-Marathon-1-722x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "mariah-carey-live-in-concert-at-borobudur",
			DestinationID: "borobudur",
			Title:        "MARIAH CAREY LIVE IN CONCERT AT BOROBUDUR",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/29749228_844150559117051_6199130556505177286_o-1024x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "muaro-madras-kecamatan-jangkat",
			DestinationID: "muaro-madras-kecamatan-jangkat",
			Title:        "muaro madras Kecamatan Jangkat",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "national-bird-contest",
			Title:        "National Bird Contest",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/bird-prambanan.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "pentas-ramayana-ballet-dan-legenda-roro-jonggrang",
			DestinationID: "ramayana",
			Title:        "Pentas Ramayana Ballet dan Legenda Roro Jonggrang",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/calendar-prambanan-ramayana-DAN-HARGA-683x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "pentas-ramayana-ballet-prambanan-dan-dramatari-legenda-roro-jonggrang-2021",
			DestinationID: "ramayana",
			Title:        "Pentas Ramayana Ballet Prambanan dan Dramatari Legenda Roro Jonggrang 2021",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/brosur-roro-jonggrang-2023-979x1024-1-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-borobudur-international-heritage-goo-wes-bike-tour",
			DestinationID: "borobudur",
			Title:        "Prambanan-Borobudur International Heritage Goo Wes Bike Tour",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/14-793x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-festival-2017-music-art-andamp-culinary",
			Title:        "Prambanan Festival 2017 : Music, Art &amp; Culinary",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20170727-WA0003-678x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-international-yoga-day",
			Title:        "Prambanan International Yoga Day",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/3-1024x747-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-jazz",
			Title:        "Prambanan Jazz",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/P_20180819_234256_HDR-1024x767-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-jazz-2017",
			Title:        "Prambanan Jazz 2017",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/DGOFA_YVwAAw8i1-1-1024x850-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-jazz-2018",
			Title:        "Prambanan Jazz 2018",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/PRAMBANAN-JAZZ-1006x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-jazz-2020-virtual-festival",
			Title:        "Prambanan Jazz 2020 Virtual Festival",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/banner-prambananjazz-2020-1024x389-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-lights-festival",
			Title:        "Prambanan Lights Festival",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20171107-WA0011-1024x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "prambanan-music-art-andamp-culture",
			Title:        "Prambanan Music, Art, &amp; Culture",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/2-737x1024-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "ramayana-ballet-prambanan-2020",
			DestinationID: "ramayana",
			Title:        "Ramayana Ballet Prambanan 2020",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/PRAMBANAN-Ramayana-Ballet-Dance-166-683x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "ramayana-ballet-prambanan-special-show",
			DestinationID: "ramayana",
			Title:        "Ramayana Ballet Prambanan Special Show",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/834fb255-1e05-43ca-b31c-f07ffbd3b9aa-475x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "ramayana-prambanan-year-end-special-show",
			DestinationID: "ramayana",
			Title:        "Ramayana Prambanan Year End Special Show",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20171127-WA0018-1024x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "ratu-boko-festival",
			DestinationID: "ratu-boko",
			Title:        "Ratu Boko Festival",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/IMG-20170831-WA0008-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "ratu-boko-yoga-andamp-meditation-day",
			DestinationID: "ratu-boko",
			Title:        "Ratu Boko Yoga &amp; Meditation Day",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/2-1-1024x920-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "safe-andamp-healthy-yoga-di-candi-prambanan",
			DestinationID: "prambanan",
			Title:        "Safe &amp; Healthy Yoga di Candi Prambanan",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/22792436_762004373998337_333300259411909728_o-725x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "sendratari-ramayana",
			DestinationID: "sendratari-ramayana",
			Title:        "Sendratari Ramayana",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "silungkang-duo",
			DestinationID: "silungkang-duo",
			Title:        "Silungkang Duo",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "Jadesta Kemenparekraf",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "sounds-of-borobudur-cultural-andamp-music-camp",
			DestinationID: "borobudur",
			Title:        "Sounds of Borobudur Cultural &amp; Music Camp",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/5-795x1024-2.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "tawur-agung",
			Title:        "Tawur Agung",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/TAWUR-AGUNG-16.3-854x1024-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "tawur-agung-prambanan",
			Title:        "Tawur Agung Prambanan",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/1-1024x960-1.png",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "tour-de-prambanan",
			Title:        "Tour de Prambanan",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/TOUR-D-PRAMBANAN-1024x761-1.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "virtual-wellness-tour-candi-borobudur",
			DestinationID: "borobudur",
			Title:        "Virtual Wellness Tour Candi Borobudur",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/Virtual-Wellness-Tour-Borobudur-768x1024-1.jpeg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "waisak-borobudur",
			DestinationID: "borobudur",
			Title:        "Waisak Borobudur",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/borobudur-waisak.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "waisak-borobudur-2563-be",
			DestinationID: "borobudur",
			Title:        "Waisak Borobudur 2563 BE",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/P_20180529_160524_vHDR_On-scaled.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "waisak-borobudur-2570-be",
			DestinationID: "borobudur",
			Title:        "Waisak Borobudur 2570 BE",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2026/05/banner-waisak-popup.webp",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "wayang-topeng-panji-sonobudoyo",
			DestinationID: "museum-sonobudoyo",
			Title:        "Pagelaran Wayang Topeng Panji",
			Description:  "Wayang Topeng Panji adalah warisan budaya UNESCO Memory of the World (2017). Kisah Panji Asmarabangun dan Dewi Candrakirana dipentaskan dalam format wayang topeng gaya Yogyakarta — perpaduan tari, topeng, musik gamelan, dan lakon klasik. Digelar rutin di Gedung Semar, Museum Sonobudoyo Unit I. Pertunjukan interaktif tanpa menghilangkan pakem aslinya, cocok untuk semua generasi.",
			Location:     "Gedung Semar, Museum Sonobudoyo Unit I, Yogyakarta",
			StartDate:    "2026-07-01",
			EndDate:      "2026-12-31",
			ImageURL:     "https://upload.wikimedia.org/wikipedia/commons/9/9b/SanabudayaMuseumEntrySign85.jpg",
			Category:     "Cultural Performance",
			Status:       "active",
			Latitude:     -7.8025,
			Longitude:    110.3635,
			MaxAttendees: 200,
			TicketPrice:  "Rp 10.000 - Rp 20.000",
			Organizer:    "Museum Sonobudoyo",
			Highlights:   event.JSONArr{"UNESCO Memory of the World", "Wayang Topeng Gaya Yogyakarta", "Kisah Panji Asmarabangun", "Gamelan Langsung", "Pertunjukan Rutin Jumat-Minggu"},
		},
		{
			ExternalID:   "yanni-live-orchestra-at-prambanan-temple",
			Title:        "YANNI Live Orchestra at Prambanan Temple",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/ip4ywr5ab6qxht62es8e_13668.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
		{
			ExternalID:   "yanni-orchestra-25th-anniversary-acropolis",
			Title:        "YANNI Orchestra “25th Anniversary Acropolis”",
			Description:  "",
			Location:     "Yogyakarta",
			StartDate:    "",
			EndDate:      "",
			ImageURL:     "https://injourneydestination.id/wp-content/uploads/2024/11/borobudurpark-1551670032344.jpg",
			Category:     "Event",
			Status:       "upcoming",
			Latitude:     0,
			Longitude:    0,
			MaxAttendees: 0,
			TicketPrice:  "Cek website resmi",
			Organizer:    "InJourney Destination Management",
			Highlights:   event.JSONArr{},
		},
	}

	inserted := 0
	updated := 0
	for _, e := range events {
		// Auto-detect status from dates if not set
		if e.Status == "" {
			e.Status = resolveEventStatus(e.StartDate, e.EndDate)
		}

		existing := event.Event{}
		if err := db.Where("external_id = ?", e.ExternalID).First(&existing).Error; err == nil {
			e.ID = existing.ID
			e.CreatedAt = existing.CreatedAt
			if err := db.Save(&e).Error; err != nil {
				log.Printf("Failed to update event %s: %v", e.ExternalID, err)
				continue
			}
			updated++
			continue
		}
		if err := db.Create(&e).Error; err != nil {
			log.Printf("Failed to seed event %s: %v", e.ExternalID, err)
			continue
		}
		inserted++
	}
	fmt.Printf("Events seeding done: %d inserted, %d updated\n", inserted, updated)
}

func resolveEventStatus(startDate, endDate string) string {
	now := time.Now()
	layout := "2006-01-02"

	if startDate != "" {
		if start, err := time.Parse(layout, startDate); err == nil && start.After(now) {
			return "upcoming"
		}
	}
	if endDate != "" {
		if end, err := time.Parse(layout, endDate); err == nil && end.Before(now) {
			return "completed"
		}
	}
	if startDate != "" {
		if _, err := time.Parse(layout, startDate); err == nil {
			return "active"
		}
	}
	return "upcoming"
}
